### ISSUE TITLE
ReadTheDocs will now no longer build the XGA docs

### ISSUE THREAD

**Issue by DavidT3** [DavidT3/XGA#1090]
Running Sphinx v3.1.2
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/xga/envs/conv-utilstelescopesupport/lib/python3.9/site-packages/sphinx/registry.py", line 419, in load_extension
    metadata = setup(app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xga/envs/conv-utilstelescopesupport/lib/python3.9/site-packages/alabaster/__init__.py", line 31, in setup
    app.require_sphinx("3.4")
  File "/home/docs/checkouts/readthedocs.org/user_builds/xga/envs/conv-utilstelescopesupport/lib/python3.9/site-packages/sphinx/application.py", line 410, in require_sphinx
    raise VersionRequirementError(version)
sphinx.errors.VersionRequirementError: 3.4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/xga/envs/conv-utilstelescopesupport/lib/python3.9/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/docs/checkouts/readthedocs.org/user_builds/xga/envs/conv-utilstelescopesupport/lib/python3.9/site-packages/sphinx/application.py", line 240, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xga/envs/conv-utilstelescopesupport/lib/python3.9/site-packages/sphinx/application.py", line 398, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xga/envs/conv-utilstelescopesupport/lib/python3.9/site-packages/sphinx/registry.py", line 422, in load_extension
    raise VersionRequirementError(
sphinx.errors.VersionRequirementError: The alabaster extension used by this project needs at least Sphinx v3.4; it therefore cannot be built with this version.

Sphinx version error:
The alabaster extension used by this project needs at least Sphinx v3.4; it therefore cannot be built with this version.

I think I need to migrate to their yaml settings file or something?

**Comment by DavidT3** [comment]
Updating sphinx version in requirements sorted this
