### ISSUE TITLE
The section of the documentation from docstrings isn't working

### ISSUE THREAD

**Issue by DavidT3** [DavidT3/XGA#522]
It's just completely blank, it hasn't successfully read any of the docstrings.

There's an error in the raw output warning that autodoc failed to import all of the modules it seems:

WARNING: autodoc: failed to import module 'imagetools.misc' from module 'xga'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/xga/envs/doc-granddocupdate/lib/python3.7/site-packages/sphinx/ext/autodoc/importer.py", line 32, in import_module
    return importlib.import_module(modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xga/envs/doc-granddocupdate/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/docs/checkouts/readthedocs.org/user_builds/xga/checkouts/doc-granddocupdate/xga/__init__.py", line 7, in <module>
    from .utils import xga_conf, CENSUS, OUTPUT, NUM_CORES, XGA_EXTRACT, BASE_XSPEC_SCRIPT, MODEL_PARS, \
  File "/home/docs/checkouts/readthedocs.org/user_builds/xga/checkouts/doc-granddocupdate/xga/utils.py", line 381, in <module>
    add_enabled_units([r200, r500, r2500, xmm_det, xmm_det])
  File "/home/docs/checkouts/readthedocs.org/user_builds/xga/envs/doc-granddocupdate/lib/python3.7/site-packages/astropy/units/core.py", line 388, in add_enabled_units
    get_current_unit_registry().add_enabled_units(units)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xga/envs/doc-granddocupdate/lib/python3.7/site-packages/astropy/units/core.py", line 199, in add_enabled_units
    "enabling them.".format(st))
ValueError: Object with name 'xmm_det' already exists in namespace. Filter the set of units to avoid name clashes before enabling them.

I really don't know what could have caused this to start happening

**Comment by DavidT3** [comment]
This does not seem to happen when I build documentation from the data driven density branch, suggesting a problem I introduced in the bug fixing branch I guess

**Comment by DavidT3** [comment]
This fix partially worked, but now I need to adjust how xspec and sas throw the error as thats happening when autodoc imports them to try and get the docstrings
