### ISSUE TITLE
v0.2.0 - Annular spectrum definition fails after generation

### ISSUE THREAD

**Issue by DavidT3** [DavidT3/XGA#598]
Generating products of type(s) annular spectrum set components: 100%|█| 5129/5129 [5:17:15<00:00,  
Traceback (most recent call last):
  File "generate_and_fit_sdss.py", line 37, in <module>
    inv_abel_dens_onion_temp(xcs_srcs, xcs_srcs.r500*1.3, 'beta', 'simple_vikhlinin_dens', 'simple_vikhlinin_temp', 'r500', temp_min_snr=35)
  File "/its/home/dt237/.conda/envs/xga_env/lib/python3.8/site-packages/xga/sourcetools/mass.py", line 149, in inv_abel_dens_onion_temp
    temp_profs = onion_deproj_temp_prof(cut_sources, cut_rads, min_snr=temp_min_snr, min_counts=spec_min_counts,
  File "/its/home/dt237/.conda/envs/xga_env/lib/python3.8/site-packages/xga/sourcetools/temperature.py", line 419, in onion_deproj_temp_prof
    ann_rads = min_snr_proj_temp_prof(sources, outer_radii, min_snr, min_width, use_combined, use_worst, lo_en,
  File "/its/home/dt237/.conda/envs/xga_env/lib/python3.8/site-packages/xga/sourcetools/temperature.py", line 266, in min_snr_proj_temp_prof
    single_temp_apec_profile(sources, all_rads, group_spec=group_spec, min_counts=min_counts, min_sn=min_sn,
  File "/its/home/dt237/.conda/envs/xga_env/lib/python3.8/site-packages/xga/xspec/run.py", line 145, in wrapper
    script_list, paths, cores, run_type, src_inds, radii, timeout = xspec_func(*args, **kwargs)
  File "/its/home/dt237/.conda/envs/xga_env/lib/python3.8/site-packages/xga/xspec/fit/profile.py", line 77, in single_temp_apec_profile
    spectrum_set(sources, radii, group_spec, min_counts, min_sn, over_sample, one_rmf, num_cores)
  File "/its/home/dt237/.conda/envs/xga_env/lib/python3.8/site-packages/xga/sas/run.py", line 237, in wrapper
    ann_spec = AnnularSpectra(ann_spec_comps[entry])
  File "/its/home/dt237/.conda/envs/xga_env/lib/python3.8/site-packages/xga/products/spec.py", line 933, in __init__
    self._all_usable = all(s.usable for s in self.all_spectra)
  File "/its/home/dt237/.conda/envs/xga_env/lib/python3.8/site-packages/xga/products/spec.py", line 933, in <genexpr>
    self._all_usable = all(s.usable for s in self.all_spectra)
AttributeError: 'NoneType' object has no attribute 'usable'

**Comment by DavidT3** [comment]
The failure is occuring during the annular declaration stage that happens in the sas_call function - this is after the multiprocessing environment is closed and all the SAS commands have been written.

I don't know how a None is getting into the list of spectra, and I also don't know why this hasn't been a problem before.

**Comment by DavidT3** [comment]
It is odd, because to even be assigned into the spectrum storage structure the objects have to have obs_id and instrument properties, it shouldn't be possible for a NoneType object to be in there - meaning perhaps that there is some obscure failure state of all_spectra that I haven't come across before?

**Comment by DavidT3** [comment]
What is even stranger is that the same bug wasn't triggered when I re-declared the ClusterSample, which in theory it should have done, as the AnnularSpectra declaration is the same there as in sas_call.

Unless of course it is one of the spectra that isn't loaded back in because there is a mismatch in available products, in which case it would be:

0500670201/0500670201_pn_XCSSDSS-480_ra260.04101999999995_dec26.623842_ri0.06041664356087991_ro0.0664583079169679_grpTrue_mincnt5_ident46773299_10_spec.fits 

I'm not sure why this would cause this error though.

**Comment by DavidT3** [comment]
So there is no ARF for that particular spectrum, which does happen occasionally unfortunately, but I still don't understand why this happened.

I may have to just run this again with some debugging stuff added to the module code and wait to see what happens.

**Comment by DavidT3** [comment]
The objects passed into the AnnularSpectra declaration **MUST** all be something other than NoneTypes, because the very first thing that AnnularSpectra does is:

        super().__init__([s.path for s in spectra], 'spectrum', "combined", "combined")

Call the BaseAggregateProduct init, with a list of paths for spectral files - so the objects in the spectra list must have a path attribute otherwise thats where the failure would be.

**Comment by DavidT3** [comment]
This bug didn't trigger when I continued the run from where it failed - so I will have to do a full re-run to see if it happens again.

**Comment by DavidT3** [comment]
I think I know what's causing the bug, but now I don't know what the bug causing the bug is.

When AnnularSpectra is declared with a set of spectra, it goes through a bunch of setup steps. One of which involves setting up the _component_products attribute:

self._component_products = {o: {i: {ai: None for ai in range(self._num_ann)}
                                        for i in self._instruments[o]} for o in self.obs_ids}

Where the _instruments attribute is set up earlier in the __init__ by cycling through the passed in spectra.

The _component_products dictionary is then filled in:

        for s in spectra:
            self._component_products[s.obs_id][s.instrument][s.annulus_ident] = s

So I can only guess that, for some reason, there is a spectrum missing that should have been generated, and so an entry is left as None - causing the later error when cycling through spectra. The trouble is, I don't understand why there would be missing spectra when the AnnularSpectrum is declared, when no generation error has been thrown.

Also, I know that this error corrects itself (or at least it doesn't fail, that doesn't necessarily mean its doing what I ask of it) when I re-run the generation.

**Comment by DavidT3** [comment]
When you just start the process again about half of the spectrumset components still appear to need generating - about 2260 out of around 4000 for the sample I'm playing with. Not sure how that plays out in terms of setting up and loading annular spectra though.

**Comment by DavidT3** [comment]
IT IS FINALLY TIME TO DO AWAY WITH THIS HATEFUL BUG

**Comment by DavidT3** [comment]
So, I suspect I finally know why this is happening, and it's a bit of a chain of unfortunate events.

The actual error is being caused by the fact that all_spectra (which is a property but does use a get method of the AnnularSpectra class (get_spectra) is actually returning a list of Nones rather than the list of Spectrum objects we expect. When we look at the contents of _component_products (what aggregate products store individual products in), we see this:

{'0861080101': {'pn': {0: None, 1: <xga.products.spec.Spectrum object at 0x2b23f3bdecd0>}, 'mos2': {0: None, 1: <xga.products.spec.Spectrum object at 0x2b23f3bdef10>}, 'mos1': {0: None, 1: <xga.products.spec.Spectrum object at 0x2b23f3bf70d0>}}}

OH NO - there are entries for annulus one that are the type of object we expect, but all the annulus 0 entries are Nones. _**This actually reflects the file situation, no annulus zero spectra/supporting files were generated for this ObsID**_. The construction function (in this case while it is loading in, though the same happened at generation time) and the AnnularSpectra init, didn't notice that there were no zeroth annulus products, and instead but the default None value there - this is the first problem.

We also find that the number of annuli is set wrong, which is the reason all_spectra is returning [None, None, None] when it should really be returning [None, None, None, <xga.products.spec.Spectrum object at 0x2b23f3bdecd0>, <xga.products.spec.Spectrum object at 0x2b23f3bdef10>, <xga.products.spec.Spectrum object at 0x2b23f3bf70d0>] (obviously would still be a problem, but would be slightly more correct).  This number of annuli is being set wrong because of the fact that only annulus 1 files/spectra are being identified and passed into the AnnularSpectra declaration - from that information in isolation I would infer that there are at least two annuli, but because I use the length of the list of annulus IDs to set the number of annuli:

        self._num_ann = len(set([s.annulus_ident for s in spectra]))

So I think I should put a check that all annulli IDs are sequential for a start - throw an informative error if not. That way this problem wouldn't have progressed this far.

Anyway - the next layer down of this problem has already been alluded to in this writeup, there are only annulus 1 files present, which obviously means that something messed up during the generation process, but it can't have been an actual error from SAS because that would have been raised. 

That means that all along it has been a relative of issue #947 (one I only discovered recently). It must be happening because a global spectrum already exists with the same settings and as such a new one is never generated, but because it isn't named in the same way it isn't added to the AnnularSpectra definition (it also definitely shouldn't be added, because the background will be pointing to a different file most likely).

So, I fix issue #947 and I probably fix this, but I will also add some extra safeguards to assuage some of the other problems I have mentioned in this comment.

**Comment by DavidT3** [comment]
Not all annular spectra components are being generated because of one line in sas.spec.py:

exists = source.get_products("spectrum", obs_id, inst, extra_key=spec_storage_name)

When it prepares the annular spectra commands it is detecting non-annular spectra as matching and thus not generating the component. While they are going to be essentially identical files, I want them to be separate as the annular spectra component file has an 'ident' that identifies which set it belongs to, and the background entry in the FITS header will be different. I did implement a 'force regen' feature it seems, and if an annular spectra set hasn't been found then all components will need to be generated I think, so I might just make that the only behaviour.

**Comment by DavidT3** [comment]
Okay, changing that made it generate more spectra (yay) but I still get the error I introduced to annular spectra that says some components are missing - now I need to figure out why that is

**Comment by DavidT3** [comment]
The remaining problem, I suspect, is that because the spec commands are set up as if for a non-annular component, and then modified afterwards, the RMF is being detected as already created so the generate rmf command is never being set up. This wouldn't be an issue APART FROM THE FACT that I'm running with one_rmf=False, which will soon become the default.
