### ISSUE TITLE
v0.2.0 - A strange bug during mass profile generation

### ISSUE THREAD

**Issue by DavidT3** [DavidT3/XGA#602]
warnings.warn("All XSPEC operations had already been run.")
Running XSPEC Simulations: 100%|█████████████████████████████████| 116/116 [00:16<00:00,  7.06it/s]
Fitting data, inverse Abel transforming, and measuring densities:   0%|    | 0/116 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/its/home/dt237/.conda/envs/xga_env/lib/python3.8/site-packages/xga/sourcetools/density.py", line 224, in _run_sb
    sb_prof = src.get_1d_brightness_profile(rad, obs_id, inst, centre, lo_en=lo_en, hi_en=hi_en,
  File "/its/home/dt237/.conda/envs/xga_env/lib/python3.8/site-packages/xga/sources/general.py", line 311, in get_1d_brightness_profile
    interim_prods = self.get_profiles("brightness", obs_id, inst, central_coord, radii, lo_en, hi_en)
  File "/its/home/dt237/.conda/envs/xga_env/lib/python3.8/site-packages/xga/sources/base.py", line 3040, in get_profiles
    raise NoProductAvailableError("Cannot find any {p} profiles matching your input.".format(p=profile_type))
xga.exceptions.NoProductAvailableError: Cannot find any brightness profiles matching your input.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generate_and_fit_sdss.py", line 40, in <module>
    inv_abel_dens_onion_temp(xcs_srcs, xcs_srcs.r500*1.3, 'beta', 'simple_vikhlinin_dens', 'simple_vikhlinin_temp', 'r500', temp_min_snr=35)
  File "/its/home/dt237/.conda/envs/xga_env/lib/python3.8/site-packages/xga/sourcetools/mass.py", line 168, in inv_abel_dens_onion_temp
    dens_profs = inv_abel_fitted_model(cut_cut_sources, sb_models_cut, fit_method, cut_cut_rads, pix_step=sb_pix_step,
  File "/its/home/dt237/.conda/envs/xga_env/lib/python3.8/site-packages/xga/sourcetools/density.py", line 445, in inv_abel_fitted_model
    sb_prof = _run_sb(src, out_rads[src_ind], use_peak, lo_en, hi_en, psf_corr, psf_model, psf_bins, psf_algo,
  File "/its/home/dt237/.conda/envs/xga_env/lib/python3.8/site-packages/xga/sourcetools/density.py", line 230, in _run_sb
    sb_prof, success = radial_brightness(rt, centre, rad, src.background_radius_factors[0],
  File "/its/home/dt237/.conda/envs/xga_env/lib/python3.8/site-packages/xga/imagetools/profile.py", line 332, in radial_brightness
    out_rads, areas = _iterative_profile(ann_masks, inn_rads, out_rads)
  File "/its/home/dt237/.conda/envs/xga_env/lib/python3.8/site-packages/xga/imagetools/profile.py", line 221, in _iterative_profile
    corr_ann_masks = annulus_masks * interloper_mask[..., None] * rt.sensor_mask[..., None] \
TypeError: 'int' object is not subscriptable

**Comment by DavidT3** [comment]
This seems to be to do with issue #578, which I solved in the contour binning branch but hadn't merged into master. As such I've merged that branch into the mass bugs branch, will double check everything is functioning, add a couple of lines, and then merge into master.

Bit ugly, but oh well
