### ISSUE TITLE
Coordinate conversion in Image derived products can return a value the same size as the array without throwing an error

### ISSUE THREAD

**Issue by DavidT3** [DavidT3/XGA#793]
Traceback (most recent call last):
  File "/home/dt237/software/anaconda3/envs/dev_xga/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/dt237/code/PycharmProjects/XGA/xga/sourcetools/match.py", line 44, in _on_obs_id
    if ex.get_exp(Quantity([ra, dec], 'deg')) != 0:
  File "/home/dt237/code/PycharmProjects/XGA/xga/products/phot.py", line 1270, in get_exp
    exp = self.data[pix_coord[1], pix_coord[0]]
IndexError: index 512 is out of bounds for axis 1 with size 512

**Comment by DavidT3** [comment]
If I had to guess it'll be in the value checks I do in coord_conv, they'll use a greater than when they should use less than or equal to or something like that

**Comment by DavidT3** [comment]
The problem was exactly what I thought it was
